### ISSUE TITLE
Current Speed Test

### ISSUE THREAD

**Issue by lukecampbell** [asascience-open/QARTOD#54]
![screen shot 2015-10-01 at 11 38 08 am](https://cloud.githubusercontent.com/assets/1155163/10225448/ea7f963e-6830-11e5-979c-e94a9c56a433.png)

- [ ] QARTOD Test implemented
- [ ] Unit Test with sample data

**Comment by ocefpaf** [comment]
Note to self: Manual [qartod_currents_manual.pdf](http://www.ioos.noaa.gov/qartod/currents/qartod_currents_manual.pdf) page 19.

Sounds like special case of the `range_check()` (Gross Range Test).
Also, the Codable Instructions do not tackle the "must be positive" condition mentioned in the test text.
